config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :home
  
  devise_for :users, controllers: { registrations: "registrations" }
  
  get "new" => "home#about"
  resources :orders
  
 

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
  class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  	if user_signed_in?
  	 redirect_to new_order_path
  	 
  	else
  		redirect_to new_user_session_path
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


	def index
		@orders = Order.all
	end

	def show
	    @order = Order.find(params[:id])
	end

	def new
	 	@order = Order.new
	end

	# 	def show
	# 		@lunch_order = LunchOrder.find(params[:name])
	# 	end

	def create

			@order = Order.new(order_params) 
			  if @order.save
	 		  redirect_to @order
	 		else
	 			render 'new'
	 		end
	end

		private
	 	  	def order_params
	 	    	params.require(:order).permit(:date, :order)
	 	  	end

 end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
	def sign_up_params
		params.require(:user).permit(:name,:email,:password,:password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name,:email,:password,:password_confirmation, :current_password)	
	end
		
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to 'Click here for orders', controller: 'orders' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Example</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<% if user_signed_in? %>
		<p>Hello Friends, <%= current_user.name %> - <%= link_to "Sign_out",destroy_user_session_path, :method =>'delete' %>
		<br>
		<% end %>

		<%= yield %>
	</body>
</html>

app/views/orders/index.html.erb
<h1>Listing Lunch Orders</h1>
 
<table>
  <tr>
    <th>Date</th>
    <th>Order</th>
  </tr>
 
  <% @orders.each do |o| %>
    <tr>
      <td><%= o.date %></td>
      <td><%= o.order %></td>
      <td><%= link_to 'Show', order_path(order) %></td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<h1>New Lunch Order</h1>
<!-- <%= link_to 'New Lunch Order', new_order_path %> -->
<%= form_for :order,url: orders_path do |f| %>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>
 
  <p>
    <%= f.label :order %><br>
    <%= f.text_area :order %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>
 
<p>
  <strong>Orders:</strong>
  <%= @order.order %>
</p>
 
<%= link_to 'Back', orders_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table border = 2>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>